#!/bin/sh
# integration-lane: test the COMBINATION of the mergeable pull requests, not the
# parts, and hand a human one reviewable merge.
#
# THE GAP THIS CLOSES
# -------------------
# Every CI gate in this repo measures the PULL REQUEST HEAD, never the merge
# result. Two pull requests that are each green against their own base can be
# broken together, and nothing looks at that combination until it is on `main` —
# where Railway auto-deploys it. The failure is not hypothetical here:
#
#   PR #1490 bundled 8 PRs by hand and found two defects "neither visible on any
#   PR alone" — a rename that git merges clean and then fails to BUILD, and a
#   `schemaVersion` collision between #1464 and #1477.
#   PR #1484 and #1503 both added fields to the same `list_criteria` response
#   rows the same day, each green apart.
#
# `pr-gate` and `publish-gate` both DETECT stuck work and neither INTEGRATES.
# This order makes the hand method (#1483, #1490) a lane.
#
# THE LANE NEVER MERGES. Decided in PRD #340 question 305, and it is a positive
# choice rather than a half-built step. The value is the combination test, which
# is fully delivered without touching the production gate; and "green" has been
# unreliable here before — PR #1346 read green on ZERO checks, which is why the
# candidate filter below refuses an empty check rollup rather than rounding it up
# to success. There is no `gh pr merge` in this file and there must never be one:
# adding it converts a reporting lane into an unattended production deploy path.
#
# WHAT A RUN DOES
#   1. Collect the open PRs that are genuinely mergeable, RE-QUERYING the lazily
#      computed mergeability rather than trusting one read.
#   2. Refuse a `schemaVersion` collision among the constituents BEFORE testing
#      the combination — it is a known collision this repo has already hit, and
#      it is cheaper to name than to discover as a build failure.
#   3. Merge each constituent onto one integration branch with --no-ff.
#   4. Verify the COMBINATION. On a failure, eject the prime suspect and re-run,
#      so the break is attributed to the pair that interacted rather than to the
#      bundle as a whole, and one bad PR delays itself instead of the set.
#   5. Push the branch and open ONE pull request against the default branch.
#   6. Mail the mayor the bundle, the size it used, and everything it excluded
#      and why. Then stop. A human decides.
#
# TWO VERIFICATION LAYERS, DELIBERATELY
# -------------------------------------
# The LOCAL verify (INTEGRATION_LANE_VERIFY) is what gives this run a verdict it
# can act on — you cannot eject a culprit you have not measured, and attribution
# needs a result within the run. It defaults to `go build ./... && go vet ./...`
# because that is the fast half that catches the observed combination-defect
# class (#1490's clean-merging rename failed at BUILD), and because the full
# `go test ./...` here inherits a known hang: the `internal/dashboard` package
# hangs against a reachable Dolt, and CI itself does not run it.
#
# The PUSHED BUNDLE PR is the second layer and the stronger one: it is a pull
# request whose head IS the combination, so the repo's whole CI runs against the
# merge result. That is the guarantee a human reads before merging. The local
# verify is the attributable pre-flight; the PR's CI is the full measurement.
# Widen the local one with INTEGRATION_LANE_VERIFY if a city wants both.
#
# WHY A LOCK
# ----------
# Two runs bundling overlapping sets would race on the same integration branch
# and could produce contradictory merges — the same class PR #1478 hardens
# pool-spawn against. `mkdir` is the lock: it is atomic on every POSIX
# filesystem, unlike a test-then-create on a lock FILE, which has a window
# between the two halves exactly wide enough for the second run to enter.
set -u

. "$(dirname "$0")/../lib/roster.sh"

sy_load_conf

# Bundle size. Read from configuration with a default of 8 (PRD #340 q305), and
# reported on every run — a three-PR bundle must never be ambiguous between "the
# queue was short" and "somebody changed the setting".
INTEGRATION_LANE_BUNDLE_SIZE="${INTEGRATION_LANE_BUNDLE_SIZE:-8}"

# The combination test. See the two-layers note above for why this is the fast
# half by default.
INTEGRATION_LANE_VERIFY="${INTEGRATION_LANE_VERIFY:-go build ./... && go vet ./...}"

# What must happen in the worktree BEFORE the verify can mean anything.
#
# This exists because omitting it made the lane useless on this very repo, in a
# way that looked exactly like a real finding. `*_templ.go` is GITIGNORED here
# (.gitignore: "regenerated by templ generate; never committed") — 0 tracked
# files against 66 `.templ` sources — so a FRESH worktree has none of them and
# `go build ./...` fails with `undefined: ProjectSpecRow` and friends before it
# ever reaches a line either constituent wrote. ci.yml runs `templ generate`
# precisely so its own build works.
#
# Without this step EVERY run reads red regardless of its constituents, ejects up
# to MAX_EJECTIONS innocent PRs with a fabricated attribution ("it builds alone
# but not beside #X"), and mails the mayor a combination alarm every cycle. A
# false alarm that names specific innocent pull requests is worse than no lane.
#
#   auto  (default) — generate templ views at the go.mod-PINNED version when the
#                     repo tracks any `.templ` file, and do nothing when it does
#                     not, so the lane stays usable on a rig without templ.
#   none            — skip preparation entirely.
#   <command>       — run this instead.
#
# Pinned, not `@latest`: generated code must match the version the module is
# built against, which is the same reason ci.yml resolves it from go.mod.
INTEGRATION_LANE_PREPARE="${INTEGRATION_LANE_PREPARE:-auto}"

# Wall-clock bound on one verify run. A verify that hangs would hold the lock and
# starve every later cycle, so it is bounded and a timeout is reported as a
# verify FAILURE rather than swallowed.
INTEGRATION_LANE_VERIFY_TIMEOUT="${INTEGRATION_LANE_VERIFY_TIMEOUT:-900}"

# How many times a run may eject a culprit and re-verify before giving up. Each
# ejection costs a full verify, and a bundle needing more than three is telling
# you the queue is unusually tangled — which is worth a human reading, not more
# machine time.
INTEGRATION_LANE_MAX_EJECTIONS="${INTEGRATION_LANE_MAX_EJECTIONS:-3}"

# Mergeability re-query. `mergeStateStatus` and `mergeable` are computed LAZILY
# by GitHub: the first read after a push is frequently UNKNOWN, and a stale DIRTY
# survives well past the merge that cleared it. A lane that trusts one read
# bundles unmergeable PRs and silently skips mergeable ones. Poll until it
# settles, then believe it.
INTEGRATION_LANE_MERGE_POLLS="${INTEGRATION_LANE_MERGE_POLLS:-5}"
INTEGRATION_LANE_MERGE_POLL_SLEEP="${INTEGRATION_LANE_MERGE_POLL_SLEEP:-3}"

# A lock older than this is treated as abandoned. Sized well above one full run.
INTEGRATION_LANE_LOCK_STALE_MIN="${INTEGRATION_LANE_LOCK_STALE_MIN:-90}"

# Narrow the lane to named rigs (space-separated). Empty means every rig.
INTEGRATION_LANE_RIGS="${INTEGRATION_LANE_RIGS:-}"

# Require an APPROVED review to enter a bundle. Default OFF, and the default is a
# judgement call worth naming rather than burying.
#
# PRD #340 puts review quality out of scope — "whether a PR should merge on its
# merits stays a human and judge-lane question" — and this lane only asks whether
# a SET is safe TOGETHER. Requiring APPROVED would also empty most bundles here,
# because a large share of PRs in this repo carry no review at all and
# `reviewDecision` is a LATCH that stays CHANGES_REQUESTED after the author has
# already pushed the fix. So the default admits an unreviewed PR and REFUSES a
# CHANGES_REQUESTED one — refuse-only, never require.
#
# The counter-argument is real: a human merging a bundle of eight is implicitly
# waving through any constituent nobody reviewed. If a city would rather bundle
# only blessed work and accept smaller bundles, this is the one line to flip —
# it is a policy setting, not a code change.
INTEGRATION_LANE_REQUIRE_APPROVAL="${INTEGRATION_LANE_REQUIRE_APPROVAL:-0}"

STATE_DIR="$(sy_state_dir)"
mkdir -p "$STATE_DIR" 2>/dev/null

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Make the worktree buildable before the verify runs. See INTEGRATION_LANE_PREPARE.
#
# Returns 0 when the tree is ready, 1 when preparation itself failed. That
# distinction is the whole point: a failure HERE is a fault in the LANE's own
# harness, not evidence about the constituents, and the caller must never eject
# anyone over it.
prepare_worktree() { # <worktree> <logfile>
  [ "$INTEGRATION_LANE_PREPARE" = "none" ] && return 0

  if [ "$INTEGRATION_LANE_PREPARE" != "auto" ]; then
    ( cd "$1" && sy_timeout "$INTEGRATION_LANE_VERIFY_TIMEOUT" \
        sh -c "$INTEGRATION_LANE_PREPARE" ) >> "$2" 2>&1
    return $?
  fi

  # A repo with no templ sources needs nothing, and must not be failed for it.
  [ -n "$(git -C "$1" ls-files '*.templ' 2>/dev/null | head -n1)" ] || return 0

  ( cd "$1" || exit 1
    tv=$(go list -m -f '{{.Version}}' github.com/a-h/templ 2>/dev/null)
    [ -n "$tv" ] || { echo "integration-lane: templ sources present but github.com/a-h/templ is not a module dependency"; exit 1; }
    go install "github.com/a-h/templ/cmd/templ@$tv" >/dev/null 2>&1 \
      || { echo "integration-lane: could not install templ $tv"; exit 1; }
    PATH="$(go env GOPATH)/bin:$PATH"
    export PATH
    sy_timeout "$INTEGRATION_LANE_VERIFY_TIMEOUT" templ generate
  ) >> "$2" 2>&1
}

# De-fang the repo's own PR-content guards when quoting a constituent's title.
#
# This lane AUTHORS a pull request into a repo that gates PR text:
#   `prd-ref guard`   refuses more than one `PRD #N` across title/body/branch
#   `issue-ref guard` matches the hyphenated `issue-N` bead token
# A bundle body that quoted eight constituent titles verbatim would carry eight
# `PRD #N` references and red its OWN checks — the lane would reliably produce
# an unmergeable bundle and blame the constituents. Quote titles with the hash
# and the hyphen removed: `PRD #91` -> `PRD 91`, `issue-249` -> `issue 249`.
# The reference is still readable by a human and no longer a machine token.
# This is the same convention CLAUDE.md prescribes for secondary mentions.
sanitize_ref_tokens() {
  sed -e 's/PRD #\([0-9]\)/PRD \1/g' \
      -e 's/PRD#\([0-9]\)/PRD \1/g' \
      -e 's/[Ii]ssue-\([0-9]\)/issue \1/g'
}

# Record an excluded pull request and WHY.
#
# Every exclusion goes through here and nowhere else. A run that reports success
# while a mergeable PR silently fell out of the set is the failure mode this
# whole file is written against: silent truncation reads as coverage.
exclude() { # <num> <title> <reason>
  printf '  #%s  %s\n      excluded: %s\n' \
    "$1" "$(printf '%s' "$2" | sanitize_ref_tokens)" "$3" >> "$TMP/excluded"
}

# Take the per-rig lock, or return 1. `mkdir` is the atomic primitive.
lane_lock() { # <rig>
  _lock="$STATE_DIR/integration-lane.$1.lock"
  if mkdir "$_lock" 2>/dev/null; then
    printf '%s\n' "$$" > "$_lock/pid" 2>/dev/null
    date -u +%s > "$_lock/started" 2>/dev/null
    return 0
  fi

  # Held. Break it only if it is older than the stale window — a run that is
  # genuinely in flight must keep the lock, and a crashed run must not hold it
  # forever. Absent or unreadable `started` counts as stale: a lock we cannot age
  # is a lock we can never release, which is worse than one extra run.
  _started=$(cat "$_lock/started" 2>/dev/null)
  _now=$(date -u +%s)
  case "$_started" in
    ''|*[!0-9]*) _age_min=$((INTEGRATION_LANE_LOCK_STALE_MIN + 1)) ;;
    *)           _age_min=$(( (_now - _started) / 60 )) ;;
  esac
  if [ "$_age_min" -gt "$INTEGRATION_LANE_LOCK_STALE_MIN" ]; then
    rm -rf "$_lock" 2>/dev/null
    if mkdir "$_lock" 2>/dev/null; then
      printf '%s\n' "$$" > "$_lock/pid" 2>/dev/null
      date -u +%s > "$_lock/started" 2>/dev/null
      return 0
    fi
  fi
  return 1
}

lane_unlock() { # <rig>
  rm -rf "$STATE_DIR/integration-lane.$1.lock" 2>/dev/null
}

# Read a PR's mergeability, re-querying while GitHub reports it as not yet
# computed. Echoes "<mergeable>\t<mergeStateStatus>".
requery_mergeable() { # <slug> <num>
  _i=0
  _m=UNKNOWN
  _s=UNKNOWN
  while [ "$_i" -lt "$INTEGRATION_LANE_MERGE_POLLS" ]; do
    _json=$(gh pr view "$2" --repo "$1" --json mergeable,mergeStateStatus 2>/dev/null)
    if [ -n "$_json" ]; then
      _m=$(printf '%s' "$_json" | jq -r '.mergeable // "UNKNOWN"' 2>/dev/null)
      _s=$(printf '%s' "$_json" | jq -r '.mergeStateStatus // "UNKNOWN"' 2>/dev/null)
      # MERGEABLE/CONFLICTING are settled answers. UNKNOWN means GitHub has not
      # finished computing the merge; asking again is the whole point.
      if [ "$_m" != "UNKNOWN" ] && [ "$_s" != "UNKNOWN" ]; then
        break
      fi
    fi
    _i=$((_i + 1))
    [ "$_i" -lt "$INTEGRATION_LANE_MERGE_POLLS" ] && sleep "$INTEGRATION_LANE_MERGE_POLL_SLEEP"
  done
  printf '%s\t%s' "${_m:-UNKNOWN}" "${_s:-UNKNOWN}"
}

# The `schemaVersion` a commit claims, or empty when the file is absent.
schema_version_at() { # <worktree> <ref>
  git -C "$1" show "$2:internal/db/dolt.go" 2>/dev/null \
    | sed -n 's/^const schemaVersion = \([0-9][0-9]*\).*$/\1/p' \
    | head -n1
}

# ---------------------------------------------------------------------------
# Per-rig run
# ---------------------------------------------------------------------------

stamp=$(date -u +%Y%m%d-%H%M%S)

rigs=$(gc rig list --json 2>/dev/null \
  | jq -r '(if type=="array" then . else (.rigs // []) end)[] | .name' 2>/dev/null)
[ -n "${INTEGRATION_LANE_RIGS:-}" ] && rigs="$INTEGRATION_LANE_RIGS"

for rig in $rigs; do
  rig_root="$(sy_city)/$rig"
  [ -d "$rig_root/.git" ] || continue

  default_branch=$(gc rig list --json 2>/dev/null | jq -r --arg r "$rig" '
    (if type=="array" then . else (.rigs // []) end)[]
    | select(.name==$r) | (.default_branch // "main")' 2>/dev/null)
  [ -n "$default_branch" ] || default_branch=main

  # owner/repo straight off the rig's own remote.
  slug=$(git -C "$rig_root" remote get-url origin 2>/dev/null \
    | sed -e 's#^git@github.com:##' -e 's#^https://github.com/##' -e 's#\.git$##')
  case "$slug" in
    */*) : ;;
    *)   continue ;;   # not a GitHub remote; nothing this lane can bundle
  esac

  lane_lock "$rig" || continue

  # Accumulate through FILES, not shell variables. The candidate rows are read in
  # a `while read` loop; feeding that from a pipe puts it in a SUBSHELL where
  # every assignment is discarded on exit — the loop would find a bundle, build
  # nothing, and exit 0. That is a dead check that looks healthy, which is the
  # failure class this pack exists to catch.
  TMP=$(mktemp -d 2>/dev/null) || { lane_unlock "$rig"; continue; }
  : > "$TMP/candidates"
  : > "$TMP/excluded"
  : > "$TMP/constituents"
  : > "$TMP/notes"

  # -------------------------------------------------------------------------
  # 1. Collect candidates
  # -------------------------------------------------------------------------
  rows=$(gh pr list --repo "$slug" --state open --base "$default_branch" \
           --limit 100 \
           --json number,title,headRefName,headRefOid,isDraft,reviewDecision,statusCheckRollup \
           2>/dev/null)
  if [ -z "$rows" ]; then
    # A gh that is missing, unauthenticated or rate-limited makes this order a
    # dead check that looks healthy. Say so rather than reporting a quiet run.
    printf 'gh returned nothing for %s — the lane could not read the queue.\n' "$slug" \
      >> "$TMP/notes"
    gc mail send mayor \
      -s "integration-lane: cannot query GitHub for $slug — this lane is not running" \
      -m "\`gh pr list --repo $slug\` returned nothing. Until this is fixed the lane
cannot tell a full merge queue from an empty one and will report nothing, which
is indistinguishable from a healthy queue.

  gh auth status
  gh api rate_limit --jq '.rate'" >/dev/null 2>&1
    rm -rf "$TMP"; lane_unlock "$rig"; continue
  fi

  printf '%s' "$rows" | jq -r '
    .[]
    | [ (.number|tostring),
        (.headRefName // ""),
        (.headRefOid // ""),
        (.isDraft|tostring),
        (.reviewDecision // ""),
        ((.statusCheckRollup // []) | length | tostring),
        ((.statusCheckRollup // [])
          | map(select(
              (.conclusion // "") == "FAILURE" or (.conclusion // "") == "CANCELLED"
              or (.conclusion // "") == "TIMED_OUT" or (.conclusion // "") == "ACTION_REQUIRED"
              or (.conclusion // "") == "STARTUP_FAILURE"
              or (.state // "") == "FAILURE" or (.state // "") == "ERROR"))
          | length | tostring),
        ((.statusCheckRollup // [])
          | map(select(
              (.status // "") == "QUEUED" or (.status // "") == "IN_PROGRESS"
              or (.status // "") == "PENDING" or (.status // "") == "WAITING"
              or (.state // "") == "PENDING"))
          | length | tostring),
        (.title // "")
      ] | @tsv' 2>/dev/null > "$TMP/rows"

  while IFS="$(printf '\t')" read -r num head oid draft review nchecks nfailed npending title; do
    [ -n "${num:-}" ] || continue

    # Never bundle a previous bundle. An integration branch is not a
    # constituent, and a lane that ate its own output would compound bundles.
    case "$head" in
      integration/*) continue ;;
    esac

    if [ "$draft" = "true" ]; then
      exclude "$num" "$title" "draft"; continue
    fi

    # `reviewDecision` is a LATCH: it stays CHANGES_REQUESTED even after the
    # author pushes a fix, and it stays that way on a PR that has since merged.
    # So it is used only to REFUSE, never to require — requiring APPROVED would
    # exclude the large share of PRs here that carry no review at all, and
    # whether a PR deserves to merge on its own merits is a human and judge-lane
    # question this lane does not answer. It only asks whether the SET is safe.
    if [ "$review" = "CHANGES_REQUESTED" ]; then
      exclude "$num" "$title" "review is CHANGES_REQUESTED"; continue
    fi
    if [ "$INTEGRATION_LANE_REQUIRE_APPROVAL" = "1" ] && [ "$review" != "APPROVED" ]; then
      exclude "$num" "$title" "no approving review (INTEGRATION_LANE_REQUIRE_APPROVAL=1)"; continue
    fi

    # ZERO checks is not success. PR #1346 read green on zero GHA checks; a lane
    # that rounds an empty rollup up to "green" bundles untested code and reports
    # a verified combination.
    if [ "${nchecks:-0}" = "0" ]; then
      exclude "$num" "$title" "no CI checks reported (an empty rollup is not green)"; continue
    fi
    if [ "${nfailed:-0}" != "0" ]; then
      exclude "$num" "$title" "$nfailed failing check(s)"; continue
    fi
    if [ "${npending:-0}" != "0" ]; then
      exclude "$num" "$title" "$npending check(s) still running"; continue
    fi

    # Mergeability LAST: it is the expensive read, so everything cheap has
    # already filtered. Re-queried, never a single lazily-computed read.
    mm=$(requery_mergeable "$slug" "$num")
    mergeable=$(printf '%s' "$mm" | cut -f1)
    mstate=$(printf '%s' "$mm" | cut -f2)
    if [ "$mergeable" != "MERGEABLE" ]; then
      exclude "$num" "$title" "not mergeable after $INTEGRATION_LANE_MERGE_POLLS re-queries (mergeable=$mergeable mergeStateStatus=$mstate)"
      continue
    fi
    case "$mstate" in
      CLEAN|HAS_HOOKS|UNSTABLE) : ;;
      BLOCKED)
        exclude "$num" "$title" "mergeStateStatus=BLOCKED (a required gate has not passed)"; continue ;;
      *)
        exclude "$num" "$title" "mergeStateStatus=$mstate"; continue ;;
    esac

    printf '%s\t%s\t%s\t%s\n' "$num" "$oid" "$head" "$title" >> "$TMP/candidates"
  done < "$TMP/rows"

  n_candidates=$(wc -l < "$TMP/candidates" 2>/dev/null | tr -d ' ')
  [ -n "$n_candidates" ] || n_candidates=0

  # -------------------------------------------------------------------------
  # 2. Nothing to add? Be silent.
  # -------------------------------------------------------------------------
  # Fewer than two mergeable PRs means there is no COMBINATION to test, and this
  # lane's whole value is the combination. Bundling one PR would create a branch
  # and a mail that tell a human nothing their existing PR did not already say.
  # No branch, no pull request, no mail.
  if [ "$n_candidates" -lt 2 ]; then
    rm -rf "$TMP"; lane_unlock "$rig"; continue
  fi

  # -------------------------------------------------------------------------
  # 3. Apply the bundle size, naming the overflow
  # -------------------------------------------------------------------------
  # Truncation is reported, never silent: an excluded PR that nobody names is
  # left behind while the run reports success.
  #
  # OLDEST FIRST. `gh pr list` returns newest-first, so capping that order starves
  # the oldest pull requests: with a queue durably above the cap they are excluded
  # EVERY run under the message "next run picks it up", which would be a lie — the
  # next run makes the same cut. Sorting ascending by number makes the oldest the
  # ones that get in, so the queue actually drains and the message is true.
  sort -n -k1,1 "$TMP/candidates" > "$TMP/candidates.sorted" 2>/dev/null \
    && mv "$TMP/candidates.sorted" "$TMP/candidates"
  if [ "$n_candidates" -gt "$INTEGRATION_LANE_BUNDLE_SIZE" ]; then
    tail -n +"$((INTEGRATION_LANE_BUNDLE_SIZE + 1))" "$TMP/candidates" \
    | while IFS="$(printf '\t')" read -r num oid head title; do
        [ -n "${num:-}" ] || continue
        exclude "$num" "$title" "queue exceeds the bundle size in use ($INTEGRATION_LANE_BUNDLE_SIZE); next run picks it up"
      done
    head -n "$INTEGRATION_LANE_BUNDLE_SIZE" "$TMP/candidates" > "$TMP/candidates.capped"
    mv "$TMP/candidates.capped" "$TMP/candidates"
  fi

  # -------------------------------------------------------------------------
  # 4. Scratch worktree off the freshly fetched default branch
  # -------------------------------------------------------------------------
  WT="$TMP/wt"
  git -C "$rig_root" fetch --quiet origin "$default_branch" >/dev/null 2>&1
  if ! git -C "$rig_root" worktree add --detach --quiet "$WT" "origin/$default_branch" >/dev/null 2>&1; then
    printf 'could not create a scratch worktree from %s\n' "$rig_root" >> "$TMP/notes"
    rm -rf "$TMP"; lane_unlock "$rig"; continue
  fi

  base_sha=$(git -C "$WT" rev-parse HEAD 2>/dev/null)
  base_schema=$(schema_version_at "$WT" HEAD)

  # Fetch every constituent head into the worktree by SHA, so the merge below
  # combines exactly the commits the candidate read measured — not whatever the
  # branch has moved to since.
  while IFS="$(printf '\t')" read -r num oid head title; do
    [ -n "${oid:-}" ] || continue
    git -C "$WT" cat-file -e "$oid^{commit}" 2>/dev/null && continue
    git -C "$WT" fetch --quiet origin "$oid" >/dev/null 2>&1 \
      || git -C "$WT" fetch --quiet origin "pull/$num/head" >/dev/null 2>&1
  done < "$TMP/candidates"

  # -------------------------------------------------------------------------
  # 5. schemaVersion collision — BEFORE the combination is tested
  # -------------------------------------------------------------------------
  # Two PRs claiming one schemaVersion is a collision this repo has already hit
  # (#1464 vs #1477, found inside bundle #1490). It merges perfectly cleanly and
  # then silently skips a migration in production, so it is worth naming as a
  # collision rather than discovering as a mysterious build or runtime failure.
  # Checked before the merge loop: a run must never spend a full verify cycle to
  # rediscover something a `git show` can answer.
  #
  # A PR CLAIMS A VERSION ONLY IF IT CHANGED ONE, MEASURED AGAINST ITS OWN
  # MERGE-BASE — never against the base TIP.
  #
  # Comparing the head to the base tip asks "does this branch differ from main
  # today?", which is true of every branch cut before main's last bump even when
  # it has not touched dolt.go at all. Measured against the live queue on
  # 2026-08-11 with main at 202: #1511 and #1504 read 198, #1484 and #1476 read
  # 196, and all four have head == merge-base and touch dolt.go zero times. The
  # tip comparison called every one of them a bump, then ejected two of them as
  # "colliding" on a version neither had claimed — 7 of 10 open PRs excluded for
  # a bump that never happened, collapsing the bundle to one.
  #
  # And the same comparison was blind in the opposite direction. When a PR bumps
  # to EXACTLY the value the base already stamps, head == base tip, so the old
  # predicate skipped it as "no bump" — the one case that matters most. Git
  # merges the identical line without a conflict and the migration is silently
  # skipped, because `migrate()` short-circuits on `ver >= schemaVersion`; that
  # is the outage class scripts/check-schema-version-bump.sh documents. A bump
  # must be STRICTLY ABOVE what the target branch stamps, so that is what is
  # enforced here rather than mere difference.
  : > "$TMP/claimed"
  : > "$TMP/keep"
  while IFS="$(printf '\t')" read -r num oid head title; do
    [ -n "${num:-}" ] || continue

    # A head we could not fetch cannot be merged OR schema-checked. Say that,
    # rather than letting the merge below fail and be reported as a conflict
    # with the bundle — a wrong reason that blames the other constituents.
    if ! git -C "$WT" cat-file -e "$oid^{commit}" 2>/dev/null; then
      exclude "$num" "$title" "could not fetch its head commit $oid from origin — not schema-checked and not merged"
      continue
    fi

    mb=$(git -C "$WT" merge-base "$base_sha" "$oid" 2>/dev/null)
    sv_head=$(schema_version_at "$WT" "$oid")
    sv_mb=""
    [ -n "$mb" ] && sv_mb=$(schema_version_at "$WT" "$mb")

    if [ -n "$sv_head" ] && [ -n "$sv_mb" ] && [ "$sv_head" != "$sv_mb" ]; then
      # This PR genuinely moves schemaVersion. Two ways that can be wrong.
      if [ -n "$base_schema" ] && [ "$sv_head" -le "$base_schema" ]; then
        exclude "$num" "$title" "schemaVersion $sv_head is not above $default_branch, which already stamps $base_schema — an equal bump merges cleanly and then skips its own migration"
        printf 'schemaVersion: #%s bumps %s -> %s, but %s already stamps %s. Equal or lower is the `ver >= schemaVersion` short-circuit outage, so it was ejected before the combination was tested.\n' \
          "$num" "$sv_mb" "$sv_head" "$default_branch" "$base_schema" >> "$TMP/notes"
        continue
      fi
      # awk, not `grep "^$sv<tab>"`: a tab inside a shell string is invisible and
      # survives exactly as long as nothing reformats this file.
      prior_num=$(awk -F'\t' -v v="$sv_head" '$1==v {print $2; exit}' "$TMP/claimed" 2>/dev/null)
      if [ -n "$prior_num" ]; then
        exclude "$num" "$title" "schemaVersion collision: both this and #$prior_num bump to $sv_head (base $default_branch stamps $base_schema)"
        printf 'schemaVersion %s is claimed by BOTH #%s and #%s — #%s was ejected before the combination was tested.\n' \
          "$sv_head" "$prior_num" "$num" "$num" >> "$TMP/notes"
        continue
      fi
      printf '%s\t%s\n' "$sv_head" "$num" >> "$TMP/claimed"
    fi
    printf '%s\t%s\t%s\t%s\n' "$num" "$oid" "$head" "$title" >> "$TMP/keep"
  done < "$TMP/candidates"
  mv "$TMP/keep" "$TMP/candidates"

  # -------------------------------------------------------------------------
  # 6. Combine, verify, and eject a culprit rather than stalling the set
  # -------------------------------------------------------------------------
  branch="integration/$stamp"
  ejections=0
  verify_log="$TMP/verify.log"
  combination=unknown

  while : ; do
    n_in=$(wc -l < "$TMP/candidates" 2>/dev/null | tr -d ' ')
    [ -n "$n_in" ] || n_in=0
    if [ "$n_in" -lt 2 ]; then
      combination=abandoned
      break
    fi

    # Fresh branch each attempt: re-bundling on top of a half-merged attempt
    # would carry the ejected commit's tree along with it.
    git -C "$WT" checkout --quiet --detach "$base_sha" >/dev/null 2>&1
    : > "$TMP/merged"

    while IFS="$(printf '\t')" read -r num oid head title; do
      [ -n "${oid:-}" ] || continue
      # --no-ff ALWAYS. The constituent's own head SHA must stay reachable from
      # the bundle tip, because that reachability is the entire mechanism by
      # which GitHub auto-closes each constituent when the bundle merges.
      if git -C "$WT" merge --no-ff --no-edit \
           -m "Integration: merge #$num" "$oid" >/dev/null 2>&1; then
        printf '%s\t%s\t%s\t%s\n' "$num" "$oid" "$head" "$title" >> "$TMP/merged"
      else
        git -C "$WT" merge --abort >/dev/null 2>&1
        exclude "$num" "$title" "conflicts with the rest of the bundle (merged clean against $default_branch alone)"
      fi
    done < "$TMP/candidates"

    cp "$TMP/merged" "$TMP/candidates"
    n_merged=$(wc -l < "$TMP/merged" 2>/dev/null | tr -d ' ')
    [ -n "$n_merged" ] || n_merged=0
    if [ "$n_merged" -lt 2 ]; then
      combination=abandoned
      break
    fi

    # Make the tree buildable first. A failure HERE is the LANE's own harness
    # breaking, not a fact about the constituents, so it must never eject anyone
    # — that is precisely how a missing `templ generate` turned into fabricated
    # "it builds alone but not beside #X" attributions against innocent PRs.
    : > "$TMP/prepare.log"
    if ! prepare_worktree "$WT" "$TMP/prepare.log"; then
      combination=unpreparable
      break
    fi

    # THE COMBINATION TEST. This is the measurement the per-PR checks cannot
    # make, because they each ran against a different base.
    if ( cd "$WT" && sy_timeout "$INTEGRATION_LANE_VERIFY_TIMEOUT" \
           sh -c "$INTEGRATION_LANE_VERIFY" ) > "$verify_log" 2>&1; then
      combination=green
      break
    fi

    combination=red
    if [ "$ejections" -ge "$INTEGRATION_LANE_MAX_EJECTIONS" ]; then
      break
    fi

    # ATTRIBUTION. The bundle is built in a fixed order, so the LAST constituent
    # merged is the one whose addition turned a set that we are about to re-test
    # into a failing one. Eject it and re-verify: if the remainder goes green,
    # the interaction is between that PR and the set below it, which is a pair
    # a human can act on — and the ejected PR delays only itself.
    #
    # This is attribution, not proof of guilt. The report says which PRs
    # interacted, because "these two together break the build" is the actionable
    # fact; deciding which of the two is wrong is a review question.
    suspect=$(tail -n1 "$TMP/merged")
    s_num=$(printf '%s' "$suspect" | cut -f1)
    s_title=$(printf '%s' "$suspect" | cut -f4)
    remaining=$(awk -F'\t' -v n="$s_num" '$1!=n {printf "%s ", $1}' "$TMP/merged")
    exclude "$s_num" "$s_title" "ejected after a COMBINATION failure — it builds alone but not beside #$(printf '%s' "$remaining" | sed 's/ $//' | sed 's/ /, #/g')"
    printf 'Combination failure attributed to #%s interacting with: %s\n%s\n' \
      "$s_num" "$remaining" "$(tail -n 25 "$verify_log" | sanitize_ref_tokens)" >> "$TMP/notes"

    awk -F'\t' -v n="$s_num" '$1!=n' "$TMP/merged" > "$TMP/candidates"
    ejections=$((ejections + 1))
  done

  # -------------------------------------------------------------------------
  # 7. Report — and hand the decision to a human
  # -------------------------------------------------------------------------
  excluded_txt=$(cat "$TMP/excluded" 2>/dev/null)
  notes_txt=$(cat "$TMP/notes" 2>/dev/null)
  n_final=$(wc -l < "$TMP/candidates" 2>/dev/null | tr -d ' ')
  [ -n "$n_final" ] || n_final=0

  constituents=$(while IFS="$(printf '\t')" read -r num oid head title; do
      [ -n "${num:-}" ] || continue
      printf '  #%s  %s\n' "$num" "$(printf '%s' "$title" | sanitize_ref_tokens)"
    done < "$TMP/candidates")

  pr_url=""
  if [ "$combination" = green ]; then
    git -C "$WT" branch -f "$branch" HEAD >/dev/null 2>&1
    if git -C "$WT" push --quiet origin "$branch:$branch" >/dev/null 2>&1; then
      body="This bundle exists because **CI measures a pull request's head, never the merge
result**. Each constituent below is green against its own base; this branch is
the first place they were ever built TOGETHER.

Combination verified locally with: \`$INTEGRATION_LANE_VERIFY\`
Bundle size in use: $INTEGRATION_LANE_BUNDLE_SIZE
Constituents ($n_final):

$constituents
## MERGE THIS WITH A MERGE COMMIT

Not squash, not rebase. Each constituent's own head commit is reachable from
this branch, and that reachability is the entire mechanism by which GitHub
auto-closes every constituent pull request when this merges. A squash flattens
those commits away: the bundle would merge, and every constituent would be left
OPEN with its code already on \`main\`, each looking unmerged. This repository
allows squash merging, so the wrong button is right there.

## What this lane did NOT do

It did not merge anything, and it never will — that decision is yours. Read the
combination's checks on this pull request before merging: they are the only
checks in this repository that measure the merge result rather than a head."
      if [ -n "$excluded_txt" ]; then
        body="$body

## Excluded from this bundle

$excluded_txt"
      fi
      if [ -n "$notes_txt" ]; then
        body="$body

## Notes

$notes_txt"
      fi
      # A failed `gh pr create` must NOT fall through as an empty URL. It did
      # once: the mayor got "one merge is waiting for you" with a blank link, no
      # error, and an orphaned integration branch on origin that nothing prunes.
      # Capture the status, and take the branch back down so a failed run leaves
      # no litter for the next one to trip over.
      if pr_url=$(gh pr create --repo "$slug" --base "$default_branch" --head "$branch" \
                    --title "Integration bundle $stamp: $n_final PRs tested together" \
                    --body "$body" 2>>"$TMP/notes"); then
        pr_url=$(printf '%s' "$pr_url" | tail -n1)
      else
        pr_url=""
      fi
      if [ -z "$pr_url" ]; then
        combination=create-failed
        if git -C "$WT" push --quiet origin ":$branch" >/dev/null 2>&1; then
          printf 'gh pr create failed; the pushed branch %s was deleted again, so nothing is orphaned.\n' \
            "$branch" >> "$TMP/notes"
        else
          printf 'gh pr create failed AND %s could not be deleted — an ORPHANED branch is on origin; remove it with: git push origin :%s\n' \
            "$branch" "$branch" >> "$TMP/notes"
        fi
        notes_txt=$(cat "$TMP/notes" 2>/dev/null)
      fi
    else
      printf 'the combination was green but pushing %s failed.\n' "$branch" >> "$TMP/notes"
      notes_txt=$(cat "$TMP/notes" 2>/dev/null)
      combination=push-failed
    fi
  fi

  git -C "$rig_root" worktree remove --force "$WT" >/dev/null 2>&1
  git -C "$rig_root" worktree prune >/dev/null 2>&1

  # A run with nothing to say says nothing. But "nothing to say" is narrow: it
  # means no bundle AND nothing excluded. An exclusion is always worth a mail —
  # an excluded PR nobody names is the silent-truncation failure.
  if [ "$combination" = abandoned ] && [ -z "$excluded_txt" ]; then
    rm -rf "$TMP"; lane_unlock "$rig"; continue
  fi

  case "$combination" in
    green)
      subject="integration-lane: $rig bundle of $n_final is green — one merge is waiting for you"
      lead="The combination BUILDS. $n_final pull requests were merged onto one branch and
verified together; nothing in this repository had measured that before.

  $pr_url

Merge it with a MERGE COMMIT, not a squash. Each constituent auto-closes on
reachability, and a squash destroys that — the bundle would land and leave every
constituent open with its code already on main.

The lane does not merge. That gate is yours and stays yours."
      ;;
    red)
      subject="integration-lane: $rig — a combination failure survived $ejections ejection(s)"
      lead="These pull requests are each green alone and BROKEN TOGETHER. The lane ejected
its prime suspect $ejections time(s) and the remainder still fails, so it did not
open a bundle. No branch was pushed.

This is the defect class the lane exists to catch: it would have reached main,
and Railway auto-deploys main."
      ;;
    unpreparable)
      subject="integration-lane: $rig — THE LANE could not prepare a buildable tree (not a combination failure)"
      lead="This is a fault in the LANE, not in any pull request. Preparation of the scratch
worktree failed before the combination was ever tested, so NOTHING here is
evidence about the constituents and nothing was ejected or blamed.

No branch was pushed and no bundle was opened. Read this as \"the lane is not
running\", not as \"the queue is broken\".

Preparation is INTEGRATION_LANE_PREPARE (currently: $INTEGRATION_LANE_PREPARE).
On this repo the default generates templ views at the go.mod-pinned version,
because *_templ.go is gitignored and a fresh worktree cannot build without it.

$(tail -n 25 "$TMP/prepare.log" 2>/dev/null | sanitize_ref_tokens)"
      ;;
    create-failed)
      subject="integration-lane: $rig combination green but opening the bundle PR FAILED"
      lead="The combination passed and \`gh pr create\` then failed, so there is NO pull
request to review — do not go looking for one. The notes below say whether the
pushed branch was cleaned up or is orphaned on origin.

Nothing is lost: the next run rebuilds the bundle from scratch."
      ;;
    push-failed)
      subject="integration-lane: $rig bundle verified green but could not be pushed"
      lead="The combination passed and then the push failed, so no pull request exists.
Nothing is lost — the next run rebuilds the bundle from scratch — but if this
repeats, the lane's push credentials are the thing to check."
      ;;
    *)
      subject="integration-lane: $rig — nothing bundled, $(printf '%s' "$excluded_txt" | grep -c 'excluded:') PR(s) excluded"
      lead="No bundle was opened: fewer than two pull requests survived the filters. Every
pull request the lane declined is named below with its reason, so nothing is
silently left behind."
      ;;
  esac

  gc mail send mayor -s "$subject" -m "$lead

Bundle size in use: $INTEGRATION_LANE_BUNDLE_SIZE (INTEGRATION_LANE_BUNDLE_SIZE)
Candidates that passed the filters: $n_candidates
Combination verify: $INTEGRATION_LANE_VERIFY
${constituents:+
Constituents ($n_final):
$constituents}
${excluded_txt:+
Excluded, and why:
$excluded_txt}
${notes_txt:+
Notes:
$notes_txt}
This lane never merges. It prepares a bundle and reports; the merge is a human
decision. See packs/README.md for the full behaviour." >/dev/null 2>&1

  rm -rf "$TMP"
  lane_unlock "$rig"
done

exit 0
